# alertmanager.yml

route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'abhinayashrinivasan2004@gmail.com'
        auth_password: ""
        from: 'abhinayashrinivasan2004@gmail.com'
        to: 'abhinayaps.22cse@kongu.edu'
        headers:
          subject: 'Prometheus Mail Alerts'
